version: '3.8'

services:
  web:
    build: .  # Собирает образ из Dockerfile
    ports:
      - "5000:5000"  # Пробрасываем порт Flask
    environment:
      - FLASK_ENV=production  # Пример переменной окружения
    restart: unless-stopped  # Автоперезапуск при падении